name: CRT EC2 Infrastructure Creation
on:
  push:
    branches: [main]
jobs:
#  build-and-analyze:
    # ... your existing CodeQL steps ...

    create-infrastructure:
      runs-on: ubuntu-latest
      # needs: build-and-analyze # Optional: Ensures infrastructure is created after CodeQL analysis
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1 # Specify your desired AWS region

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.x" # Specify your desired Python version

        - name: Install dependencies
          run:
            python -m pip install --upgrade pip
            pip install boto3 
            pip install -r requirements.txt # If your Python code has dependencies

        - name: Run Python script to create infrastructure
          run: python crt-ec2.py
#            env:
#              # Define any environment variables required by your Python script
#              AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#              AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
